version: '3.8'
services:
  koala-messaging-publisher:
    image: koala-messaging-publisher
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Development