apiVersion: apps/v1
kind: Deployment
metadata:
  name: koala-message-publisher-service
spec:
    replicas: 1
    strategy: Recreate
    selector:
        matchLabels:
          deploy: koala-message-publisher-service
    template:
        metadata:
          labels:
            deploy: koala-message-publisher-service
        spec:
          containers:
          - name: koala-message-publisher-service
            image: koala-message-publisher-service
            ports:
              - containerPort: 5001
            env:
              - name: DOTNET_ENVIRONMENT
                value: "Production"