apiVersion: v1
kind: Service
metadata:
    name: "koalacluster-bc81"
    labels:
        app: "koalacluster-bc81"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "koalacluster-bc81"